---
- name: Update apt package index
  apt:
    update_cache: yes

- name: Upgrade specific packages
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages_to_update }}"

- name: Install additional utilities
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ additional_packages }}"
