---
- name: Ensure custom groups are present
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ custom_groups }}"

- name: Manage user accounts
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    state: "{{ item.state }}"
    groups: "{{ item.groups | join(',') }}"
    password: "{{ item.password }}"
  loop: "{{ users }}"
  when: item.state == "present"

- name: Manage user SSH key
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.ssh_key }}"
  loop: "{{ users }}"
  when:
    - item.state == "present"
    - item.ssh_key is defined

- name: Remove user accounts
  user:
    name: "{{ item.name }}"
    state: absent
    remove: yes
  loop: "{{ users }}"
  when: item.state == "absent"


